# 应用名
spring:
  application:
    name: nacos-provider-movie-my
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        # sentinel控制台和当前应用进行数据传递的端口号
        port: 8729
        # 当前应用连接的sentinel控制台
        dashboard: localhost:8080

server:
  port: 7000 #表示此服务的tomcat端口号